### ISSUE TITLE
Registration contact

### ISSUE THREAD

**Issue by jimmybaker** [unixcharles/acme-client#125]
In your readme, the registration uses a "mailto:" in front of the email address when registering a new client. Is this required for emails or just a type-o?

**Comment by unixcharles** [comment]
They specification says URLs but does not give more details, just a series or examples.

See [rfc.section.7.1.2](https://ietf-wg-acme.github.io/acme/#rfc.section.7.1.2]

From the doc, it seem that any type of URLs would work, `tel:+15555555555`, `https://example.com/contact`, etc.

This is probably up to the server implementation to decide what is valid or not.

I assume that if you were to not have at least one email `mailto:email@format` entry, you will not receive notification for expiring or revoked certificates and other service alert that might require action on your part. [community.letsencrypt.org](https://community.letsencrypt.org) is probably a good place to ask for details on this.

**Comment by cpu** [comment]
> This is probably up to the server implementation to decide what is valid or not.

Since https://github.com/ietf-wg-acme/acme/pull/291 supporting `mailto:` is "mandatory to  implement" but all other URI schemes are up to the implementer to decide whether or not to support, using an `unsupportedContact` error type for unsupported URI schemes.

Let's Encrypt/Boulder specifically [only supports `mailto`](https://github.com/letsencrypt/boulder/blob/fbd87b17576aaf47b238c384a179f192a1cace5f/ra/ra.go#L372:L374). Though at present, we have a [documented divergence](https://github.com/letsencrypt/boulder/blob/6155ec9ad228a88966489072d95c8189ba51f35c/docs/acme-divergences.md#section-57) from the spec where we return a `invalidEmail` error instead of `unsupportedContact` (the code predates the spec change).

Hope this helps!
