### ISSUE TITLE
GET as POST

### ISSUE THREAD

**Issue by maths22** [unixcharles/acme-client#166]
Given https://community.letsencrypt.org/t/acme-v2-scheduled-deprecation-of-unauthenticated-resource-gets/74380 , acme-client should transition to using (or maybe allowing/defaulting to) POST-as-GETs instead of regular GETs sometime in the next couple months.  (Feel free to close if I'm misunderstanding the underlying acme change)

**Comment by unixcharles** [comment]
I was aware of the issue but didn't had time to implement post-as-get yet.

**Comment by maths22** [comment]
That's very fair.  Just figured I'd open the issue for tracking since I didn't see one already.

**Comment by jsha** [comment]
In terms of timing, we are [beginning the first phase of our ACMEv1 deprecation now](https://community.letsencrypt.org/t/end-of-life-plan-for-acmev1/88430). I suspect this will lead a lot of people on older versions of acme-client to upgrade in the coming month, in order to get ACMEv2 support. If the version available for them to upgrade had POST-as-GET support, that would save them from having to upgrade again in the future.

**Comment by unixcharles** [comment]
Implemented in v2.0.5. Thanks to @github1
