### ISSUE TITLE
Acme::Client::Error::Unauthorized: Error creating new cert for www subdomain

### ISSUE THREAD

**Issue by kyledrake** [unixcharles/acme-client#71]
I'm not yet sure if this is a bug related to my branch/merging or a documentation error.
Following the directions on the README:

```
csr = Acme::Client::CertificateRequest.new names: ["kyledrake.net", "www.kyledrake.net"]
=> #<Acme::Client::CertificateRequest:0xOBSCURED
 @common_name="kyledrake.net",
 @digest=#<OpenSSL::Digest::SHA256: OBSCURED>,
 @names=["kyledrake.net", "www.kyledrake.net"],
 @private_key=#<OpenSSL::PKey::RSA:0xOBSCURED>,
 @subject={"CN"=>"kyledrake.net"}>

certificate = letsencrypt.new_certificate csr
Acme::Client::Error::Unauthorized: Error creating new cert :: Authorizations for these names not found or expired: www.kyledrake.net
from OBSCURED/ruby/2.3.0/acme-client-d0ced992bfe4/lib/acme/client/faraday_middleware.rb:52:in `on_complete'
```

If I remove the subdomain `www.kyledrake.net`, it works fine. Is there an extra step for adding a subdomain that isn't demonstrated on the README (for example, a need to also verify the `www.*`)? The code I've written for this so far is here: https://github.com/neocities/neocities/blob/master/workers/lets_encrypt_worker.rb#L22

Apologies in advance if this is a bad issue filing.

**Comment by jhass** [comment]
Yes, you have to validate each FQDN separately prior to asking for a cert that includes them.

The readme is indeed misleading here. Since it's desirable to demonstrate the common name/SAN property of the list, the comment above should probably make very clear that each FQDN needs to have been successfully validated and that the above example of validating a FQDN does not validate all FQDNs used in this example.

**Comment by unixcharles** [comment]
I think you are right, the README is misleading. Thanks for letting us know.
